cmake_minimum_required(VERSION 3.20)

function(quicksort input_list output_var)
    list(LENGTH ${input_list} len)
    if(len LESS_EQUAL 1)
        set(${output_var} ${${input_list}} PARENT_SCOPE)
        return()
    endif()
    math(EXPR pivot_idx "${len} / 2")
    list(GET ${input_list} ${pivot_idx} pivot)
    set(left "")
    set(middle "")
    set(right "")
    foreach(val IN LISTS ${input_list})
        if(val LESS pivot)
            list(APPEND left ${val})
        elseif(val EQUAL pivot)
            list(APPEND middle ${val})
        else()
            list(APPEND right ${val})
        endif()
    endforeach()
    quicksort(left left_sorted)
    quicksort(right right_sorted)
    set(${output_var} ${left_sorted} ${middle} ${right_sorted} PARENT_SCOPE)
endfunction()

set(data 3 6 8 10 1 2 1)
quicksort(data result)
message(STATUS "Sorted: ${result}")
