DEFINE QUICKSORT INPUT ARR
    IF COUNT(ARR) <= 1 THEN RETURN ARR
    SET PIVOT = ARR[COUNT(ARR) / 2]
    SET LEFT = SUBSET OF ARR WHERE VALUE < PIVOT
    SET MIDDLE = SUBSET OF ARR WHERE VALUE = PIVOT
    SET RIGHT = SUBSET OF ARR WHERE VALUE > PIVOT
    RETURN QUICKSORT(LEFT) + MIDDLE + QUICKSORT(RIGHT)
END DEFINE

PRINT QUICKSORT([3, 6, 8, 10, 1, 2, 1])
