C QUICKSORT DEMONSTRATION
M1	ACCEPT ARR SIZE OF 6
	ACCEPT ARR LOAD [5, 2, 8, 1, 9, 3]
	PERFORM QUICKSORT
	PRINT ARR

QUICKSORT	ACCEPT ARR SIZE OF LEN
	IF LEN <= 1
		JUMP DONE
	ENDIF
	ACCEPT PIVOT ARR(1)
	COMPUTE I = 1, J = LEN
	LOOP:
		WHILE ARR(I) < PIVOT
			COMPUTE I = I + 1
		ENDWHILE
		WHILE ARR(J) > PIVOT
			COMPUTE J = J - 1
		ENDWHILE
		IF I < J
			SWAP ARR(I) ARR(J)
		ENDIF
	DONE:	ACCEPT

END	PILOT