cmake_minimum_required(VERSION 3.15)
project(PancakeSort)

function(flip arr_var k)
    set(arr ${${arr_var}})
    set(left 0)
    set(right ${k})
    while(left LESS right)
        list(GET arr ${left} lv)
        list(GET arr ${right} rv)
        list(REMOVE_AT arr ${left})
        list(INSERT arr ${left} ${rv})
        list(REMOVE_AT arr ${right})
        list(INSERT arr ${right} ${lv})
        math(EXPR left "${left} + 1")
        math(EXPR right "${right} - 1")
    endwhile()
    set(${arr_var} ${arr} PARENT_SCOPE)
endfunction()

function(pancake_sort arr_var)
    set(arr ${${arr_var}})
    list(LENGTH arr n)
    set(size ${n})
    while(size GREATER 1)
        set(max_idx 0)
        set(i 1)
        while(i LESS size)
            list(GET arr ${i} iv)
            list(GET arr ${max_idx} mv)
            if(iv GREATER mv)
                set(max_idx ${i})
            endif()
            math(EXPR i "${i} + 1")
        endwhile()
        math(EXPR size_m1 "${size} - 1")
        if(NOT max_idx EQUAL size_m1)
            if(NOT max_idx EQUAL 0)
                flip(arr ${max_idx})
            endif()
            flip(arr ${size_m1})
        endif()
        math(EXPR size "${size} - 1")
    endwhile()
    set(${arr_var} ${arr} PARENT_SCOPE)
endfunction()

set(arr 3 6 2 7 4 1 5)
pancake_sort(arr)
message(STATUS "Sorted: ${arr}")
