(defun flip (arr k)
  (let ((left 0) (right k) tmp)
    (while (< left right)
      (setq tmp (aref arr left))
      (aset arr left (aref arr right))
      (aset arr right tmp)
      (setq left (1+ left))
      (setq right (1- right)))))

(defun find-max-idx (arr size)
  (let ((max-idx 0))
    (dotimes (i size)
      (when (> (aref arr i) (aref arr max-idx))
        (setq max-idx i)))
    max-idx))

(defun pancake-sort (arr)
  (let ((size (length arr)))
    (while (> size 1)
      (let ((mi (find-max-idx arr size)))
        (when (/= mi (1- size))
          (when (/= mi 0) (flip arr mi))
          (flip arr (1- size))))
      (setq size (1- size))))
  arr)

(let ((arr (vector 3 6 2 7 4 1 5)))
  (message "%S" (pancake-sort arr)))
