(DEFUN PANCAKESORT (ARR)
    (PROG (N I J TEMP)
        (SETQ N (LENGTH ARR))
        (SETQ I 0)
        LOOP1 (COND ((>= I (- N 1)) (RETURN ARR)))
        (SETQ J 0)
        LOOP2 (COND ((>= J (- N I 1)) (GO LOOP1)))
        (COND ((> (NTH ARR J) (NTH ARR (+ J 1)))
            (SETQ TEMP (NTH ARR J))
            (SETF (NTH ARR J) (NTH ARR (+ J 1)))
            (SETF (NTH ARR (+ J 1)) TEMP)))
        (SETQ J (+ J 1))
        (GO LOOP2)))

(PRINT (PANCAKESORT '(5 2 8 1 9 3)))
