PANCAKE
    N ARR,N,SIZE,MAXI,I,LEFT,RIGHT,TMP
    S ARR(1)=3,ARR(2)=6,ARR(3)=2,ARR(4)=7
    S ARR(5)=4,ARR(6)=1,ARR(7)=5
    S N=7,SIZE=N
OUTER
    I SIZE<=1 G DONE
    S MAXI=1
    S I=2
FINDMAX
    I I>SIZE G DOFLIP
    I ARR(I)>ARR(MAXI) S MAXI=I
    S I=I+1
    G FINDMAX
DOFLIP
    I MAXI=SIZE G DECR
    I MAXI=1 G FLIP2
    S LEFT=1,RIGHT=MAXI
FLIP1
    I LEFT>=RIGHT G FLIP2
    S TMP=ARR(LEFT)
    S ARR(LEFT)=ARR(RIGHT)
    S ARR(RIGHT)=TMP
    S LEFT=LEFT+1,RIGHT=RIGHT-1
    G FLIP1
FLIP2
    S LEFT=1,RIGHT=SIZE
FLIP3
    I LEFT>=RIGHT G DECR
    S TMP=ARR(LEFT)
    S ARR(LEFT)=ARR(RIGHT)
    S ARR(RIGHT)=TMP
    S LEFT=LEFT+1,RIGHT=RIGHT-1
    G FLIP3
DECR
    S SIZE=SIZE-1
    G OUTER
DONE
    S I=1
PRINT
    I I>N Q
    W ARR(I)," "
    S I=I+1
    G PRINT
