(def comb-sort (arr)
  (let n (len arr)
    (with (gap n sorted nil)
      (while (no sorted)
        (= gap (max 1 (int:/ gap 1.3)))
        (if (is gap 1) (= sorted t))
        (for i 0 (- n gap 1)
          (if (> (arr i) (arr (+ i gap)))
            (do
              (= tmp (arr i))
              (= (arr i) (arr (+ i gap)))
              (= (arr (+ i gap)) tmp)
              (= sorted nil)))))
      arr)))
