function(comb_sort arr_name n)
    set(arr ${${arr_name}})
    set(gap ${n})
    set(sorted FALSE)
    while(NOT sorted)
        math(EXPR gap "${gap} * 10 / 13")
        if(gap LESS_EQUAL 1)
            set(gap 1)
            set(sorted TRUE)
        endif()
        set(i 0)
        math(EXPR limit "${n} - ${gap}")
        while(i LESS limit)
            math(EXPR j "${i} + ${gap}")
            list(GET arr ${i} a)
            list(GET arr ${j} b)
            if(a GREATER b)
                list(REMOVE_AT arr ${i})
                list(INSERT arr ${i} ${b})
                list(REMOVE_AT arr ${j})
                list(INSERT arr ${j} ${a})
                set(sorted FALSE)
            endif()
            math(EXPR i "${i} + 1")
        endwhile()
    endwhile()
    set(${arr_name} ${arr} PARENT_SCOPE)
endfunction()
