(defun comb-sort (arr)
  (let* ((n (length arr))
         (gap n)
         (sorted nil))
    (while (not sorted)
      (setq gap (max 1 (floor (/ gap 1.3))))
      (setq sorted (= gap 1))
      (cl-loop for i from 0 below (- n gap) do
        (when (> (aref arr i) (aref arr (+ i gap)))
          (let ((tmp (aref arr i)))
            (aset arr i (aref arr (+ i gap)))
            (aset arr (+ i gap) tmp))
          (setq sorted nil))))
    arr))
