(define (comb-sort arr)
  (let ((gap (vector-length arr))
        (swapped #t))
    (while (or (> gap 1) swapped)
      (set! gap (quotient (* gap 10) 13))
      (if (< gap 1) (set! gap 1))
      (set! swapped #f)
      (let loop ((i 0))
        (when (< i (- (vector-length arr) gap))
          (when (> (vector-ref arr i) (vector-ref arr (+ i gap)))
            (let ((temp (vector-ref arr i)))
              (vector-set! arr i (vector-ref arr (+ i gap)))
              (vector-set! arr (+ i gap) temp))
            (set! swapped #t))
          (loop (+ i 1)))))
    arr))

(define sample #(5 2 8 1 9 3))
(display (comb-sort sample))
(newline)
