(defn comb-sort [arr]
  (def n (length arr))
  (var gap n)
  (var sorted false)
  (while (not sorted)
    (set gap (max 1 (math/floor (/ gap 1.3))))
    (when (= gap 1) (set sorted true))
    (for i 0 (- n gap)
      (when (> (arr i) (arr (+ i gap)))
        (def tmp (arr i))
        (put arr i (arr (+ i gap)))
        (put arr (+ i gap) tmp)
        (set sorted false))))
  arr)
