COMBSORT(ARR,N)
 NEW GAP,SORTED,I,J,TMP
 SET GAP=N,SORTED=0
 FOR  QUIT:SORTED  DO
 . SET GAP=$$NEWGAP(GAP)
 . IF GAP=1 SET SORTED=1
 . FOR I=1:1:N-GAP DO
 .. SET J=I+GAP
 .. IF ARR(I)>ARR(J) DO
 ... SET TMP=ARR(I)
 ... SET ARR(I)=ARR(J)
 ... SET ARR(J)=TMP
 ... SET SORTED=0
 QUIT

NEWGAP(G)
 NEW NG
 SET NG=G*10\13
 IF NG<1 SET NG=1
 QUIT NG
