*COMB SORT PILOT PROGRAM
*
T   ACCEPT A1, A2, A3, A4, A5, A6
:DATA
5 2 8 1 9 3
*
T   COMPUTE GAP = 6
T   COMPUTE SWAPPED = 1
*
:LOOP
C   COMPUTE GAP = GAP * 10 / 13
C   ACCEPT GAP
C   COMPUTE SWAPPED = 0
C   ACCEPT SWAPPED
C   TYPE GAP, SWAPPED
J   LOOP
*
:END
T   TYPE A1, A2, A3, A4, A5, A6
E
