(define (comb-sort! vec)
  (let* ((n (vector-length vec))
         (gap n)
         (sorted #f))
    (let loop ()
      (set! gap (max 1 (exact (floor (/ gap 1.3)))))
      (set! sorted (= gap 1))
      (let inner ((i 0))
        (when (< (+ i gap) n)
          (when (> (vector-ref vec i) (vector-ref vec (+ i gap)))
            (let ((tmp (vector-ref vec i)))
              (vector-set! vec i (vector-ref vec (+ i gap)))
              (vector-set! vec (+ i gap) tmp))
            (set! sorted #f))
          (inner (+ i 1))))
      (unless sorted (loop)))
    vec))
