(define (shellsort arr)
  (let ((n (vector-length arr)))
    (let loop-gap ((gap 1))
      (if (<= gap n)
        (loop-gap (* gap 3 1))
        (let loop-main ((gap gap))
          (if (> gap 0)
            (let loop-i ((gap gap) (i gap))
              (if (< i n)
                (let* ((temp (vector-ref arr i))
                       (j (loop-j arr gap i temp)))
                  (vector-set! arr j temp)
                  (loop-i gap (+ i 1)))
                (loop-main (quotient gap 3))))
            arr))))
    (define (loop-j arr gap i temp)
      (if (or (< i gap) (<= (vector-ref arr (- i gap)) temp))
        i
        (begin (vector-set! arr i (vector-ref arr (- i gap)))
               (loop-j arr gap (- i gap) temp)))))
  arr)
(display (shellsort #(5 2 8 1 9 3)))
