(define (shellsort arr)
  (let ((n (vector-length arr)))
    (let loop-gap ((gap 1))
      (if (<= gap n)
        (loop-gap (+ (* gap 3) 1))
        (let loop-main ((gap gap))
          (if (> gap 0)
            (let loop-i ((i gap))
              (if (< i n)
                (let* ((temp (vector-ref arr i))
                       (j (let loop-j ((j i))
                            (if (and (>= j gap)
                                    (> (vector-ref arr (- j gap)) temp))
                              (begin
                                (vector-set! arr j (vector-ref arr (- j gap)))
                                (loop-j (- j gap)))
                              j))))
                  (vector-set! arr j temp)
                  (loop-i (+ i 1)))
                (loop-main (quotient gap 3))))
            arr)))))
    arr))
(display (shellsort #(5 2 8 1 9 3)))
