(define (shellsort arr)
    (let ((n (vector-length arr)))
        (let gap-loop ((gap (quotient n 2)))
            (when (> gap 0)
                (let i-loop ((i gap))
                    (when (< i n)
                        (let ((temp (vector-ref arr i)))
                            (let j-loop ((j i))
                                (when (and (>= j gap)
                                          (> (vector-ref arr (- j gap)) temp))
                                    (vector-set! arr j (vector-ref arr (- j gap)))
                                    (j-loop (- j gap))))
                            (vector-set! arr i temp)
                            (i-loop (+ i 1)))))
                (gap-loop (quotient gap 2))))
        arr))
