(define (shellsort arr)
    (let ((n (vector-length arr)))
        (define (gap-loop gap)
            (when (> gap 0)
                (define (i-loop i)
                    (when (< i n)
                        (let ((temp (vector-ref arr i)))
                            (define (j-loop j)
                                (when (and (>= j gap)
                                          (> (vector-ref arr (- j gap)) temp))
                                    (vector-set! arr j (vector-ref arr (- j gap)))
                                    (j-loop (- j gap))))
                            (j-loop i)
                            (vector-set! arr i temp)
                            (i-loop (+ i 1)))))
                (i-loop gap)
                (gap-loop (quotient gap 2))))
        (gap-loop (quotient n 2))
        arr))
