cmake_minimum_required(VERSION 3.10)
project(BubbleSort)

set(arr 64 34 25 12 22 11 90)
list(LENGTH arr n)

set(swapped TRUE)
while(swapped)
    set(swapped FALSE)
    math(EXPR limit "${n} - 1")
    set(i 0)
    while(i LESS limit)
        math(EXPR j "${i} + 1")
        list(GET arr ${i} xi)
        list(GET arr ${j} xj)
        if(xi GREATER xj)
            list(REMOVE_AT arr ${i})
            list(INSERT arr ${i} ${xj})
            list(REMOVE_AT arr ${j})
            list(INSERT arr ${j} ${xi})
            set(swapped TRUE)
        endif()
        math(EXPR i "${i} + 1")
    endwhile()
    math(EXPR n "${n} - 1")
endwhile()

message(STATUS "Sorted: ${arr}")
