(define (bubble-sort! vec)
  (let ((n (vector-length vec)))
    (let loop ((n n))
      (when (> n 1)
        (let inner ((i 0) (swapped #f))
          (if (< i (- n 1))
              (if (> (vector-ref vec i) (vector-ref vec (+ i 1)))
                  (begin
                    (let ((tmp (vector-ref vec i)))
                      (vector-set! vec i (vector-ref vec (+ i 1)))
                      (vector-set! vec (+ i 1) tmp))
                    (inner (+ i 1) #t))
                  (inner (+ i 1) swapped))
              (when swapped (loop (- n 1)))))))))

(define arr (vector 64 34 25 12 22 11 90))
(bubble-sort! arr)
(display arr)
(newline)
