cmake_minimum_required(VERSION 3.10)
project(StoogeSort)

function(stooge_sort arr_var first last)
    list(GET ${arr_var} ${first} a)
    list(GET ${arr_var} ${last} b)
    if(a GREATER b)
        list(REMOVE_AT ${arr_var} ${last})
        list(INSERT ${arr_var} ${last} ${a})
        list(REMOVE_AT ${arr_var} ${first})
        list(INSERT ${arr_var} ${first} ${b})
        set(${arr_var} ${${arr_var}} PARENT_SCOPE)
    endif()
    math(EXPR n "${last} - ${first} + 1")
    if(n GREATER 2)
        math(EXPR t "${n} * 2 / 3")
        math(EXPR m1 "${first} + ${t} - 1")
        stooge_sort(${arr_var} ${first} ${m1})
        math(EXPR m2 "${last} - ${t} + 1")
        stooge_sort(${arr_var} ${m2} ${last})
        stooge_sort(${arr_var} ${first} ${m1})
        set(${arr_var} ${${arr_var}} PARENT_SCOPE)
    endif()
endfunction()

set(arr 3 1 4 1 5 9 2 6)
list(LENGTH arr n)
math(EXPR last "${n} - 1")
stooge_sort(arr 0 ${last})
message(STATUS "Sorted: ${arr}")
