(defun stooge-sort (arr first last)
    (when (> (aref arr first) (aref arr last))
        (let ((tmp (aref arr first)))
            (aset arr first (aref arr last))
            (aset arr last tmp)))
    (let ((n (- last first -1)))
        (when (> n 2)
            (let ((tt (/ (* n 2) 3)))
                (stooge-sort arr first (+ first tt -1))
                (stooge-sort arr (- last tt -1) last)
                (stooge-sort arr first (+ first tt -1))))))

(let ((arr (vector 3 1 4 1 5 9 2 6)))
    (stooge-sort arr 0 (1- (length arr)))
    (message "%S" arr))
