(defn stooge-sort [arr first last]
    (when (> (get arr first) (get arr last))
        (setv tmp (get arr first))
        (setv (get arr first) (get arr last))
        (setv (get arr last) tmp))
    (setv n (- last first -1))
    (when (> n 2)
        (setv t (// (* n 2) 3))
        (stooge-sort arr first (+ first t -1))
        (stooge-sort arr (- last t -1) last)
        (stooge-sort arr first (+ first t -1))))

(setv arr [3 1 4 1 5 9 2 6])
(stooge-sort arr 0 (- (len arr) 1))
(print arr)
