(DEFINEQ STOOGESORT
  (LAMBDA (A I J)
    (COND
      ((LESSP (CAR (NTH J A)) (CAR (NTH I A)))
        (RPLACD (NTH I A) (CAR (NTH J A)))
        (RPLACD (NTH J A) (CAR (NTH I A)))))
      ((GREATERP (DIFFERENCE J I) 1)
        (SETQ T (QUOTIENT (PLUS (DIFFERENCE J I) 1) 3))
        (STOOGESORT A I (DIFFERENCE J T))
        (STOOGESORT A (PLUS I T) J)
        (STOOGESORT A I (DIFFERENCE J T))))))

(SETQ ARR (LIST 5 2 8 1 9 3))
(STOOGESORT ARR 0 5)
(PRINT ARR)
