(defun stooge-sort (arr first last)
    (when (> (aref arr first) (aref arr last))
        (let ((tmp (aref arr first)))
            (setf (aref arr first) (aref arr last))
            (setf (aref arr last) tmp)))
    (when (> (- last first -1) 2)
        (let ((t-val (floor (* (- last first -1) 2) 3)))
            (stooge-sort arr first (+ first t-val -1))
            (stooge-sort arr (- last t-val -1) last)
            (stooge-sort arr first (+ first t-val -1)))))

(let ((arr (make-array 8 :initial-contents '(3 1 4 1 5 9 2 6))))
    (stooge-sort arr 0 7)
    (print arr))
