(define (heapsort arr)
  (let ((n (vector-length arr)))
    (let loop-build ((i (quotient n 2)))
      (if (>= i 0)
        (begin
          (siftdown arr i n)
          (loop-build (- i 1)))))
    (let loop-sort ((i (- n 1)))
      (if (> i 0)
        (begin
          (let ((temp (vector-ref arr 0)))
            (vector-set! arr 0 (vector-ref arr i))
            (vector-set! arr i temp))
          (siftdown arr 0 i)
          (loop-sort (- i 1)))))))

(define (siftdown arr idx n)
  (let ((largest idx)
        (left (+ (* 2 idx) 1))
        (right (+ (* 2 idx) 2)))
    (if (and (< left n) (> (vector-ref arr left) (vector-ref arr largest)))
      (set! largest left))
    (if (and (< right n) (> (vector-ref arr right) (vector-ref arr largest)))
      (set! largest right))
    (if (not (= largest idx))
      (begin
        (let ((temp (vector-ref arr idx)))
          (vector-set! arr idx (vector-ref arr largest))
          (vector-set! arr largest temp))
        (siftdown arr largest n)))))

(let ((arr (vector 5 2 8 1 9 3)))
  (heapsort arr)
  (display arr))
