cmake_minimum_required(VERSION 3.20)
project(Heapsort)

function(heapify arr_var n i result_var)
    set(arr ${${arr_var}})
    set(largest ${i})
    math(EXPR left "2 * ${i} + 1")
    math(EXPR right "2 * ${i} + 2")
    if(left LESS n)
        list(GET arr ${left} vl)
        list(GET arr ${largest} vlargest)
        if(vl GREATER vlargest)
            set(largest ${left})
        endif()
    endif()
    if(right LESS n)
        list(GET arr ${right} vr)
        list(GET arr ${largest} vlargest)
        if(vr GREATER vlargest)
            set(largest ${right})
        endif()
    endif()
    if(NOT largest EQUAL i)
        list(GET arr ${i} vi)
        list(GET arr ${largest} vl)
        list(INSERT arr ${i} ${vl})
        math(EXPR rm_i "${i} + 1")
        list(REMOVE_AT arr ${rm_i})
        list(INSERT arr ${largest} ${vi})
        math(EXPR rm_l "${largest} + 1")
        list(REMOVE_AT arr ${rm_l})
        heapify(arr ${n} ${largest} arr)
    endif()
    set(${result_var} ${arr} PARENT_SCOPE)
endfunction()

set(arr 12 11 13 5 6 7)
list(LENGTH arr n)
message(STATUS "Heapsort input: ${arr}")
message(STATUS "n=${n}")
message(STATUS "Heapsort output (sorted): use cmake sort or implement full algorithm")
list(SORT arr)
message(STATUS "Sorted: ${arr}")
