(define (heapify arr n i)
  (let* ((largest i)
         (left (+ (* 2 i) 1))
         (right (+ (* 2 i) 2))
         (largest (if (and (< left n) (> (vector-ref arr left) (vector-ref arr largest))) left largest))
         (largest (if (and (< right n) (> (vector-ref arr right) (vector-ref arr largest))) right largest)))
    (when (not (= largest i))
      (let ((tmp (vector-ref arr i)))
        (vector-set! arr i (vector-ref arr largest))
        (vector-set! arr largest tmp))
      (heapify arr n largest))))

(define (heapsort arr)
  (let ((n (vector-length arr)))
    (let loop ((i (- (quotient n 2) 1)))
      (when (>= i 0) (heapify arr n i) (loop (- i 1))))
    (let loop ((i (- n 1)))
      (when (> i 0)
        (let ((tmp (vector-ref arr 0)))
          (vector-set! arr 0 (vector-ref arr i))
          (vector-set! arr i tmp))
        (heapify arr i 0)
        (loop (- i 1)))))
  arr)

(let ((arr (vector 12 11 13 5 6 7)))
  (heapsort arr)
  (display arr) (newline))
