(defun selection-sort (arr / n i j min-idx tmp)
  (setq n (length arr))
  (setq i 0)
  (while (< i (1- n))
    (setq min-idx i)
    (setq j (1+ i))
    (while (< j n)
      (if (< (nth j arr) (nth min-idx arr))
        (setq min-idx j))
      (setq j (1+ j)))
    (setq tmp (nth i arr))
    (setq arr (substitute (nth min-idx arr) (nth i arr) arr :start2 i :count 1))
    (setq arr (substitute tmp (nth min-idx arr) arr :start2 min-idx :count 1))
    (setq i (1+ i)))
  arr)
