function(selection_sort result)
    set(arr ${ARGN})
    list(LENGTH arr n)
    math(EXPR n_minus_1 "${n} - 1")
    foreach(i RANGE 0 ${n_minus_1})
        set(min_idx ${i})
        math(EXPR i_plus_1 "${i} + 1")
        if(${i_plus_1} LESS ${n})
            foreach(j RANGE ${i_plus_1} ${n_minus_1})
                list(GET arr ${j} val_j)
                list(GET arr ${min_idx} val_min)
                if(${val_j} LESS ${val_min})
                    set(min_idx ${j})
                endif()
            endforeach()
        endif()
        list(GET arr ${i} val_i)
        list(GET arr ${min_idx} val_min)
        list(REMOVE_AT arr ${i})
        list(INSERT arr ${i} ${val_min})
        list(REMOVE_AT arr ${min_idx})
        list(INSERT arr ${min_idx} ${val_i})
    endforeach()
    set(${result} ${arr} PARENT_SCOPE)
endfunction()
