SELSORT(ARR,N)
    NEW I,J,MINIDX,TMP
    FOR I=1:1:N-1 DO
    . SET MINIDX=I
    . FOR J=I+1:1:N DO
    . . IF ARR(J)<ARR(MINIDX) SET MINIDX=J
    . SET TMP=ARR(I),ARR(I)=ARR(MINIDX),ARR(MINIDX)=TMP
    QUIT
