(def selectionSort (arr)
     (let ((n (len arr)))
       (dotimes (i n arr)
         (let ((minIdx i))
           (dotimes-from (j (+ i 1) n)
             (when (< (nth j arr) (nth minIdx arr))
               (set! minIdx j)))
           (let ((tmp (nth i arr)))
             (set-nth! arr i (nth minIdx arr))
             (set-nth! arr minIdx tmp))))))
