(define (selection-sort lst)
  (define (remove-first x lst)
    (cond ((null? lst) '())
          ((= (car lst) x) (cdr lst))
          (else (cons (car lst) (remove-first x (cdr lst))))))
  (if (null? lst)
      '()
      (let ((m (apply min lst)))
        (cons m (selection-sort (remove-first m lst))))))
