(defun counting-sort (arr)
  (if (null arr)
      arr
    (let* ((min-val (apply #'min arr))
           (max-val (apply #'max arr))
           (range (1+ (- max-val min-val)))
           (count (make-vector range 0))
           (n (length arr))
           (output (make-vector n 0))
           (vec (vconcat arr)))
      (dotimes (i n)
        (let ((v (aref vec i)))
          (aset count (- v min-val) (1+ (aref count (- v min-val))))))
      (let ((i 1))
        (while (< i range)
          (aset count i (+ (aref count i) (aref count (1- i))))
          (setq i (1+ i))))
      (let ((i (1- n)))
        (while (>= i 0)
          (let* ((v (aref vec i))
                 (idx (- v min-val))
                 (pos (1- (aref count idx))))
            (aset count idx pos)
            (aset output pos v))
          (setq i (1- i))))
      (append output nil))))

(message "%s" (counting-sort '(4 2 2 8 3 3 1)))
