(define (counting-sort arr)
  (if (null? arr)
      arr
      (let* ((min-val (apply min arr))
             (max-val (apply max arr))
             (range (+ 1 (- max-val min-val)))
             (count (make-vector range 0))
             (n (length arr))
             (output (make-vector n 0))
             (vec (list->vector arr)))
        (let loop ((i 0))
          (when (< i n)
            (vector-set! count (- (vector-ref vec i) min-val)
                         (+ 1 (vector-ref count (- (vector-ref vec i) min-val))))
            (loop (+ i 1))))
        (let loop ((i 1))
          (when (< i range)
            (vector-set! count i (+ (vector-ref count i) (vector-ref count (- i 1))))
            (loop (+ i 1))))
        (let loop ((i (- n 1)))
          (when (>= i 0)
            (let* ((v (vector-ref vec i))
                   (idx (- v min-val))
                   (pos (- (vector-ref count idx) 1)))
              (vector-set! count idx pos)
              (vector-set! output pos v))
            (loop (- i 1))))
        (vector->list output))))

(display (counting-sort '(4 2 2 8 3 3 1)))
(newline)
