(defun is-sorted (arr)
  (let ((n (length arr))
        (sorted t)
        (i 0))
    (while (and sorted (< i (1- n)))
      (when (> (nth i arr) (nth (1+ i) arr))
        (setq sorted nil))
      (setq i (1+ i)))
    sorted))

(defun shuffle (arr)
  (let ((v (vconcat arr))
        (n (length arr)))
    (dotimes (i (1- n))
      (let* ((i (- n i 1))
             (j (random (1+ i)))
             (tmp (aref v i)))
        (aset v i (aref v j))
        (aset v j tmp)))
    (append v nil)))

(defun bogosort (arr)
  (while (not (is-sorted arr))
    (setq arr (shuffle arr)))
  arr)

(message "%s" (bogosort '(3 1 4 1 5 9 2 6)))
