function(insertion_sort result_var)
    set(arr ${ARGN})
    list(LENGTH arr n)
    math(EXPR last "${n} - 1")
    foreach(i RANGE 1 ${last})
        list(GET arr ${i} key)
        math(EXPR j "${i} - 1")
        while(${j} GREATER_EQUAL 0)
            list(GET arr ${j} val)
            if(${val} GREATER ${key})
                math(EXPR jp1 "${j} + 1")
                list(INSERT arr ${jp1} ${val})
                list(REMOVE_AT arr ${j})
                math(EXPR j "${j} - 1")
            else()
                break()
            endif()
        endwhile()
    endforeach()
    set(${result_var} ${arr} PARENT_SCOPE)
endfunction()
