(function insertionSort (arr)
    (set n (arr count))
    (set i 1)
    (while (< i n)
        (set key (arr objectAtIndex:i))
        (set j (- i 1))
        (while (and (>= j 0) (> (arr objectAtIndex:j) key))
            (arr replaceObjectAtIndex:(+ j 1) withObject:(arr objectAtIndex:j))
            (set j (- j 1)))
        (arr replaceObjectAtIndex:(+ j 1) withObject:key)
        (set i (+ i 1)))
    arr)
