(define (bitonicsort arr lo cnt dir)
  (if (> cnt 1)
    (let ((k (quotient cnt 2)))
      (bitonicsort arr lo k 1)
      (bitonicsort arr (+ lo k) k 0)
      (bitonicmerge arr lo cnt dir))
    arr))

(define (bitonicmerge arr lo cnt dir)
  (if (> cnt 1)
    (let ((k (quotient cnt 2)))
      (do ((i lo (+ i 1)))
          ((>= i (+ lo (- cnt k))))
        (when (eq (> (vector-ref arr i) (vector-ref arr (+ i k))) (= dir 1))
          (let ((tmp (vector-ref arr i)))
            (vector-set! arr i (vector-ref arr (+ i k)))
            (vector-set! arr (+ i k) tmp))))
      (bitonicmerge arr lo k dir)
      (bitonicmerge arr (+ lo k) k dir))
    arr))

(let ((arr (vector 5 2 8 1 9 3 7 4)))
  (bitonicsort arr 0 8 1)
  (display arr))
