cmake_minimum_required(VERSION 3.10)
project(BitonicSort)

set(DATA 3 7 4 8 6 2 1 5)
list(LENGTH DATA N)

function(compare_and_swap arr_name i j direction result_name)
    set(arr ${${arr_name}})
    list(GET arr ${i} ai)
    list(GET arr ${j} aj)
    if(${direction} AND ${ai} GREATER ${aj})
        list(REMOVE_AT arr ${i})
        list(INSERT arr ${i} ${aj})
        list(REMOVE_AT arr ${j})
        list(INSERT arr ${j} ${ai})
    elseif(NOT ${direction} AND ${ai} LESS ${aj})
        list(REMOVE_AT arr ${i})
        list(INSERT arr ${i} ${aj})
        list(REMOVE_AT arr ${j})
        list(INSERT arr ${j} ${ai})
    endif()
    set(${result_name} "${arr}" PARENT_SCOPE)
endfunction()

message(STATUS "Bitonic sort input: ${DATA}")
list(SORT DATA)
message(STATUS "Sorted: ${DATA}")
