(defun compare-and-swap (arr i j direction)
  (let ((ai (aref arr i))
        (aj (aref arr j)))
    (when (eq direction (> ai aj))
      (aset arr i aj)
      (aset arr j ai))))

(defun bitonic-merge (arr lo cnt direction)
  (when (> cnt 1)
    (let ((k (/ cnt 2)))
      (cl-loop for i from lo below (+ lo k)
               do (compare-and-swap arr i (+ i k) direction))
      (bitonic-merge arr lo k direction)
      (bitonic-merge arr (+ lo k) k direction))))

(defun bitonic-sort (arr lo cnt direction)
  (when (> cnt 1)
    (let ((k (/ cnt 2)))
      (bitonic-sort arr lo k t)
      (bitonic-sort arr (+ lo k) k nil)
      (bitonic-merge arr lo cnt direction))))

(let ((data (vector 3 7 4 8 6 2 1 5)))
  (bitonic-sort data 0 (length data) t)
  (message "%s" (mapcar #'identity data)))
