cmake_minimum_required(VERSION 3.10)
project(RadixSort)

function(counting_sort arr_var exp result_var)
    set(arr ${${arr_var}})
    list(LENGTH arr n)
    set(result "")
    foreach(d RANGE 0 9)
        foreach(x ${arr})
            math(EXPR digit "${x} / ${exp} % 10" OUTPUT_FORMAT DECIMAL)
            if(${digit} EQUAL ${d})
                list(APPEND result ${x})
            endif()
        endforeach()
    endforeach()
    set(${result_var} ${result} PARENT_SCOPE)
endfunction()

function(radix_sort arr_var result_var)
    set(arr ${${arr_var}})
    if(NOT arr)
        set(${result_var} "" PARENT_SCOPE)
        return()
    endif()
    set(max_val 0)
    foreach(x ${arr})
        if(${x} GREATER ${max_val})
            set(max_val ${x})
        endif()
    endforeach()
    set(exp 1)
    set(result ${arr})
    math(EXPR check "${max_val} / ${exp}")
    while(${check} GREATER 0)
        counting_sort(result ${exp} result)
        math(EXPR exp "${exp} * 10")
        math(EXPR check "${max_val} / ${exp}")
    endwhile()
    set(${result_var} ${result} PARENT_SCOPE)
endfunction()

set(arr 170 45 75 90 802 24 2 66)
radix_sort(arr sorted)
message(STATUS "Sorted: ${sorted}")
