(DEFINEQ RADIXSORT
  (LAMBDA (ARR)
    (PROG (MAX EXP)
      (SETQ MAX (APPLY 'MAX ARR))
      (SETQ EXP 1)
      (WHILE (GREATERP (QUOTIENT MAX EXP) 0)
        (SETQ ARR (COUNTINGSORTBYEXP ARR EXP))
        (SETQ EXP (TIMES EXP 10))
      )
      (RETURN ARR)
    )
  )
)

(DEFINEQ COUNTINGSORTBYEXP
  (LAMBDA (ARR EXP)
    ARR
  )
)

(PRINT (RADIXSORT '(5 2 8 1 9 3)))
