(define (counting-sort lst exp)
  (let* ((n (length lst))
         (v (list->vector lst))
         (output (make-vector n 0))
         (count (make-vector 10 0)))
    (let loop ((i 0))
      (when (< i n)
        (let ((idx (modulo (quotient (vector-ref v i) exp) 10)))
          (vector-set! count idx (+ (vector-ref count idx) 1))
          (loop (+ i 1)))))
    (let loop ((i 1))
      (when (< i 10)
        (vector-set! count i (+ (vector-ref count i) (vector-ref count (- i 1))))
        (loop (+ i 1))))
    (let loop ((i (- n 1)))
      (when (>= i 0)
        (let* ((x (vector-ref v i))
               (idx (modulo (quotient x exp) 10))
               (pos (- (vector-ref count idx) 1)))
          (vector-set! count idx pos)
          (vector-set! output pos x)
          (loop (- i 1)))))
    (vector->list output)))

(define (radix-sort lst)
  (if (null? lst) lst
      (let* ((max-val (apply max lst))
             (exp 1))
        (let loop ((arr lst) (e 1))
          (if (> (quotient max-val e) 0)
              (loop (counting-sort arr e) (* e 10))
              arr)))))

(display (radix-sort '(170 45 75 90 802 24 2 66)))
(newline)
