function(gnome_sort)
    set(arr 5 3 8 1 9 2 7 4 6 0)
    list(LENGTH arr n)
    set(i 0)
    while(i LESS n)
        if(i EQUAL 0)
            math(EXPR i "${i} + 1")
        else()
            math(EXPR prev "${i} - 1")
            list(GET arr ${i} ai)
            list(GET arr ${prev} aprev)
            if(ai GREATER_EQUAL aprev)
                math(EXPR i "${i} + 1")
            else()
                list(INSERT arr ${prev} ${ai})
                list(REMOVE_AT arr ${i})
                list(INSERT arr ${i} ${aprev})
                list(REMOVE_AT arr ${prev})
                if(i GREATER 0)
                    math(EXPR i "${i} - 1")
                endif()
            endif()
        endif()
    endwhile()
    message(STATUS "Sorted: ${arr}")
endfunction()
