(defun gnome-sort (arr)
  (let ((n (length arr))
        (i 0))
    (while (< i n)
      (if (or (= i 0) (>= (aref arr i) (aref arr (1- i))))
          (setq i (1+ i))
        (let ((tmp (aref arr i)))
          (aset arr i (aref arr (1- i)))
          (aset arr (1- i) tmp)
          (setq i (1- i)))))
    arr))
