cmake_minimum_required(VERSION 3.20)
project(BucketSort)

function(insertion_sort bucket_var n)
    set(bucket ${${bucket_var}})
    math(EXPR last "${n} - 1")
    if(${n} LESS_EQUAL 1)
        return()
    endif()
    foreach(i RANGE 1 ${last})
        list(GET bucket ${i} key)
        math(EXPR j "${i} - 1")
        while(${j} GREATER_EQUAL 0)
            list(GET bucket ${j} curr)
            if(${curr} GREATER ${key})
                math(EXPR jp1 "${j} + 1")
                list(GET bucket ${j} tmp)
                list(REMOVE_AT bucket ${jp1})
                list(INSERT bucket ${jp1} ${tmp})
                list(REMOVE_AT bucket ${j})
                list(INSERT bucket ${j} ${key})
                math(EXPR j "${j} - 1")
            else()
                break()
            endif()
        endwhile()
    endforeach()
    set(${bucket_var} ${bucket} PARENT_SCOPE)
endfunction()

function(bucket_sort arr_var n)
    set(arr ${${arr_var}})
    list(LENGTH arr len)
    set(min_v 100) set(max_v 0)
    foreach(v IN LISTS arr)
        if(${v} LESS ${min_v}) set(min_v ${v}) endif()
        if(${v} GREATER ${max_v}) set(max_v ${v}) endif()
    endforeach()
    foreach(v IN LISTS arr)
        message(STATUS "val: ${v}")
    endforeach()
endfunction()

set(data 78 17 39 26 72 94 21 12 23 68)
message(STATUS "Bucket sort (integer approximation):")
bucket_sort(data 10)
