cmake_minimum_required(VERSION 3.15)
project(TimSort)

function(insertion_sort arr_var left right)
    set(arr ${${arr_var}})
    math(EXPR start "${left} + 1")
    foreach(i RANGE ${start} ${right})
        list(GET arr ${i} key)
        math(EXPR j "${i} - 1")
        while(${j} GREATER_EQUAL ${left})
            list(GET arr ${j} prev)
            if(${prev} GREATER ${key})
                math(EXPR jplus "${j} + 1")
                list(INSERT arr ${jplus} ${prev})
                list(REMOVE_AT arr ${j})
                math(EXPR j "${j} - 1")
            else()
                break()
            endif()
        endwhile()
        math(EXPR jplus "${j} + 1")
        list(INSERT arr ${jplus} ${key})
        list(REMOVE_AT arr ${i})
    endforeach()
    set(${arr_var} ${arr} PARENT_SCOPE)
endfunction()

function(timsort arr_var)
    set(arr ${${arr_var}})
    list(LENGTH arr n)
    set(min_run 32)
    set(i 0)
    while(${i} LESS ${n})
        math(EXPR right_val "${i} + ${min_run} - 1")
        math(EXPR n_minus1 "${n} - 1")
        if(${right_val} GREATER ${n_minus1})
            set(right_val ${n_minus1})
        endif()
        insertion_sort(arr ${i} ${right_val})
        math(EXPR i "${i} + ${min_run}")
    endwhile()
    set(${arr_var} ${arr} PARENT_SCOPE)
endfunction()

set(data 5 2 8 1 9 3 7 4 6)
timsort(data)
message(STATUS "Sorted: ${data}")
