(define (cocktailsort arr)
  (let ((n (vector-length arr)))
    (let loop ((i 0))
      (if (< i n)
        (let ((swapped (ref #f)))
          (do ((k 0 (+ k 1)))
            ((>= k (- n i 1)))
            (when (> (vector-ref arr k) (vector-ref arr (+ k 1)))
              (let ((temp (vector-ref arr k)))
                (vector-set! arr k (vector-ref arr (+ k 1)))
                (vector-set! arr (+ k 1) temp)
                (set! swapped #t))))
          (if (not (unbox swapped))
            arr
            (begin
              (set! swapped #f)
              (do ((k (- n i 2) (- k 1)))
                ((< k 0))
                (when (> (vector-ref arr k) (vector-ref arr (+ k 1)))
                  (let ((temp (vector-ref arr k)))
                    (vector-set! arr k (vector-ref arr (+ k 1)))
                    (vector-set! arr (+ k 1) temp)
                    (set! swapped #t))))
              (loop (+ i 1))))))))
    arr))

(print (cocktailsort (vector 5 2 8 1 9 3)))
