cmake_minimum_required(VERSION 3.15)

function(cocktail_sort input_list output_var)
    list(LENGTH ${input_list} n)
    set(arr ${${input_list}})
    set(swapped TRUE)
    set(start 0)
    math(EXPR end "${n} - 1")
    while(swapped)
        set(swapped FALSE)
        set(i ${start})
        while(i LESS end)
            math(EXPR i1 "${i} + 1")
            list(GET arr ${i} a)
            list(GET arr ${i1} b)
            if(a GREATER b)
                list(REMOVE_AT arr ${i})
                list(INSERT arr ${i} ${b})
                list(REMOVE_AT arr ${i1})
                list(INSERT arr ${i1} ${a})
                set(swapped TRUE)
            endif()
            math(EXPR i "${i} + 1")
        endwhile()
        if(NOT swapped)
            break()
        endif()
        set(swapped FALSE)
        math(EXPR end "${end} - 1")
        set(i ${end})
        while(i GREATER_EQUAL start)
            math(EXPR i1 "${i} + 1")
            list(GET arr ${i} a)
            list(GET arr ${i1} b)
            if(a GREATER b)
                list(REMOVE_AT arr ${i})
                list(INSERT arr ${i} ${b})
                list(REMOVE_AT arr ${i1})
                list(INSERT arr ${i1} ${a})
                set(swapped TRUE)
            endif()
            math(EXPR i "${i} - 1")
        endwhile()
        math(EXPR start "${start} + 1")
    endwhile()
    set(${output_var} ${arr} PARENT_SCOPE)
endfunction()
