(defun cocktail-sort (arr)
  (let* ((n (length arr))
         (swapped t)
         (start 0)
         (ending (1- n)))
    (while swapped
      (setq swapped nil)
      (let ((i start))
        (while (< i ending)
          (let ((a (aref arr i))
                (b (aref arr (1+ i))))
            (when (> a b)
              (aset arr i b)
              (aset arr (1+ i) a)
              (setq swapped t)))
          (setq i (1+ i))))
      (when swapped
        (setq swapped nil)
        (setq ending (1- ending))
        (let ((i (1- ending)))
          (while (>= i start)
            (let ((a (aref arr i))
                  (b (aref arr (1+ i))))
              (when (> a b)
                (aset arr i b)
                (aset arr (1+ i) a)
                (setq swapped t)))
            (setq i (1- i))))
        (setq start (1+ start))))
    arr))
