COCKTAIL(ARR,N)
    NEW SWAPPED,START,END,I,TMP
    SET SWAPPED=1,START=0,END=N-1
    FOR  QUIT:'SWAPPED  DO
    . SET SWAPPED=0
    . FOR I=START:1:END-1  DO
    . . IF ARR(I)>ARR(I+1) DO
    . . . SET TMP=ARR(I),ARR(I)=ARR(I+1),ARR(I+1)=TMP,SWAPPED=1
    . QUIT:'SWAPPED
    . SET SWAPPED=0,END=END-1
    . FOR I=END-1:-1:START  DO
    . . IF ARR(I)>ARR(I+1) DO
    . . . SET TMP=ARR(I),ARR(I)=ARR(I+1),ARR(I+1)=TMP,SWAPPED=1
    . SET START=START+1
    QUIT
