(define (cocktail-sort! vec)
  (let ((n (vector-length vec))
        (swapped #t)
        (start 0))
    (let loop ((end (- n 1)))
      (when swapped
        (set! swapped #f)
        (let fwd ((i start))
          (when (< i end)
            (when (> (vector-ref vec i) (vector-ref vec (+ i 1)))
              (let ((tmp (vector-ref vec i)))
                (vector-set! vec i (vector-ref vec (+ i 1)))
                (vector-set! vec (+ i 1) tmp)
                (set! swapped #t)))
            (fwd (+ i 1))))
        (when swapped
          (set! swapped #f)
          (let bwd ((i (- end 1)))
            (when (>= i start)
              (when (> (vector-ref vec i) (vector-ref vec (+ i 1)))
                (let ((tmp (vector-ref vec i)))
                  (vector-set! vec i (vector-ref vec (+ i 1)))
                  (vector-set! vec (+ i 1) tmp)
                  (set! swapped #t)))
              (bwd (- i 1))))
          (set! start (+ start 1))
          (loop (- end 1)))))
    vec))
