(define (cyclesort arr)
  (let* ((n (length arr))
         (vec (list->vector arr)))
    (let loop ((pos 0))
      (if (< pos n)
        (let* ((item (vector-ref vec pos))
               (cycles (count (lambda (i)
                                (and (not (= i pos))
                                     (< (vector-ref vec i) item)))
                              (iota n))))
          (if (> cycles 0)
            (begin
              (let skip-loop ((p pos))
                (if (= (vector-ref vec p) item)
                  (skip-loop (+ p 1))))
              (let ((temp (vector-ref vec pos)))
                (vector-set! vec pos item)
                (vector-set! vec pos temp))
              (let cycle-loop ((c cycles))
                (if (> c 0)
                  (begin
                    (set! cycles 0)
                    (set! cycles (count (lambda (i)
                                          (and (not (= i pos))
                                               (< (vector-ref vec i) item)))
                                        (iota n)))
                    (let skip-loop2 ((p pos))
                      (if (= (vector-ref vec p) item)
                        (skip-loop2 (+ p 1))))
                    (let ((temp (vector-ref vec pos)))
                      (vector-set! vec pos item)
                      (vector-set! vec pos temp))
                    (cycle-loop (- c 1)))))))
          (loop (+ pos 1)))
        (vector->list vec)))))

(display (cyclesort '(5 2 8 1 9 3)))
