cmake_minimum_required(VERSION 3.20)
project(CycleSort)

set(arr 5 4 3 2 1)
list(LENGTH arr n)

function(cycle_sort arr_var n result_var)
    set(arr ${${arr_var}})
    math(EXPR limit "${n} - 2")
    foreach(cycle_start RANGE 0 ${limit})
        list(GET arr ${cycle_start} item)
        set(pos ${cycle_start})
        math(EXPR start_i "${cycle_start} + 1")
        math(EXPR end_i "${n} - 1")
        foreach(i RANGE ${start_i} ${end_i})
            list(GET arr ${i} v)
            if(v LESS item)
                math(EXPR pos "${pos} + 1")
            endif()
        endforeach()
        if(NOT pos EQUAL cycle_start)
            list(GET arr ${pos} tmp)
            list(REMOVE_AT arr ${pos})
            list(INSERT arr ${pos} ${item})
            set(item ${tmp})
        endif()
    endforeach()
    set(${result_var} "${arr}" PARENT_SCOPE)
endfunction()

cycle_sort(arr ${n} sorted)
message(STATUS "Sorted: ${sorted}")
