(defun cycle-sort (arr)
  (let* ((n (length arr))
         (writes 0))
    (dotimes (cycle-start (1- n))
      (let ((item (aref arr cycle-start))
            (pos cycle-start))
        (cl-loop for i from (1+ cycle-start) below n
                 when (< (aref arr i) item) do (cl-incf pos))
        (unless (= pos cycle-start)
          (while (= item (aref arr pos)) (cl-incf pos))
          (let ((tmp (aref arr pos)))
            (aset arr pos item)
            (setq item tmp))
          (cl-incf writes)
          (while (/= pos cycle-start)
            (setq pos cycle-start)
            (cl-loop for i from (1+ cycle-start) below n
                     when (< (aref arr i) item) do (cl-incf pos))
            (while (= item (aref arr pos)) (cl-incf pos))
            (let ((t2 (aref arr pos)))
              (aset arr pos item)
              (setq item t2))
            (cl-incf writes)))))
    writes))

(let ((arr (vector 5 4 3 2 1)))
  (cycle-sort arr)
  (message "%s" arr))
