(define (cyclesort arr)
  (define n (length arr))
  (define vec (list->vector arr))
  (let ((pos 0))
    (define (outer-loop pos)
      (if (< pos n)
        (let* ((item (vector-ref vec pos))
               (cycles (length (filter (lambda (i)
                                         (and (not (= i pos))
                                              (< (vector-ref vec i) item)))
                                       (iota n)))))
          (if (> cycles 0)
            (begin
              (let inner-loop ((p pos))
                (if (= (vector-ref vec p) item)
                  (inner-loop (+ p 1))))
              (let ((temp (vector-ref vec pos)))
                (vector-set! vec pos item)
                (vector-set! vec pos temp))))
          (outer-loop (+ pos 1)))
        (vector->list vec)))
    (outer-loop 0)))

(display (cyclesort '(5 2 8 1 9 3)))
(newline)
