CYCLESRT ;
    NEW ARR,N,CS,ITEM,POS,I,TMP,WRITES
    SET ARR(1)=5,ARR(2)=4,ARR(3)=3,ARR(4)=2,ARR(5)=1
    SET N=5,WRITES=0
    FOR CS=1:1:N-1 DO
    . SET ITEM=ARR(CS),POS=CS
    . FOR I=CS+1:1:N DO
    . . IF ARR(I)<ITEM SET POS=POS+1
    . IF POS'=CS DO
    . . FOR  QUIT:ARR(POS)'=ITEM  SET POS=POS+1
    . . SET TMP=ARR(POS),ARR(POS)=ITEM,ITEM=TMP
    . . SET WRITES=WRITES+1
    . . FOR  QUIT:POS=CS  DO
    . . . SET POS=CS
    . . . FOR I=CS+1:1:N DO
    . . . . IF ARR(I)<ITEM SET POS=POS+1
    . . . FOR  QUIT:ARR(POS)'=ITEM  SET POS=POS+1
    . . . SET TMP=ARR(POS),ARR(POS)=ITEM,ITEM=TMP
    . . . SET WRITES=WRITES+1
    FOR I=1:1:N WRITE ARR(I)," "
    WRITE !
    QUIT
