(define (cycle-sort! vec)
  (let* ((n (vector-length vec))
         (writes 0))
    (let outer ((cycle-start 0))
      (when (< cycle-start (- n 1))
        (let ((item (vector-ref vec cycle-start))
              (pos cycle-start))
          (let count ((i (+ cycle-start 1)))
            (when (< i n)
              (when (< (vector-ref vec i) item)
                (set! pos (+ pos 1)))
              (count (+ i 1))))
          (when (not (= pos cycle-start))
            (let skip ()
              (when (= item (vector-ref vec pos))
                (set! pos (+ pos 1))
                (skip)))
            (let ((tmp (vector-ref vec pos)))
              (vector-set! vec pos item)
              (set! item tmp))
            (set! writes (+ writes 1))
            (let inner ()
              (when (not (= pos cycle-start))
                (set! pos cycle-start)
                (let cnt ((i (+ cycle-start 1)))
                  (when (< i n)
                    (when (< (vector-ref vec i) item)
                      (set! pos (+ pos 1)))
                    (cnt (+ i 1))))
                (let sk ()
                  (when (= item (vector-ref vec pos))
                    (set! pos (+ pos 1))
                    (sk)))
                (let ((t (vector-ref vec pos)))
                  (vector-set! vec pos item)
                  (set! item t))
                (set! writes (+ writes 1))
                (inner))))
          (outer (+ cycle-start 1)))))
    writes))

(let ((v (vector 5 4 3 2 1)))
  (cycle-sort! v)
  (display v)
  (newline))
