#lang typed/racket

(: cycle-sort! (-> (Vectorof Integer) Integer))
(define (cycle-sort! vec)
  (define n (vector-length vec))
  (define writes : Integer 0)
  (for ([cycle-start (in-range (- n 1))])
    (define item : Integer (vector-ref vec cycle-start))
    (define pos : Integer cycle-start)
    (for ([i (in-range (+ cycle-start 1) n)])
      (when (< (vector-ref vec i) item)
        (set! pos (+ pos 1))))
    (unless (= pos cycle-start)
      (let skip : Void ()
        (when (= item (vector-ref vec pos))
          (set! pos (+ pos 1))
          (skip)))
      (define tmp : Integer (vector-ref vec pos))
      (vector-set! vec pos item)
      (set! item tmp)
      (set! writes (+ writes 1))
      (let loop : Void ()
        (unless (= pos cycle-start)
          (set! pos cycle-start)
          (for ([i (in-range (+ cycle-start 1) n)])
            (when (< (vector-ref vec i) item)
              (set! pos (+ pos 1))))
          (let sk : Void ()
            (when (= item (vector-ref vec pos))
              (set! pos (+ pos 1))
              (sk)))
          (define t : Integer (vector-ref vec pos))
          (vector-set! vec pos item)
          (set! item t)
          (set! writes (+ writes 1))
          (loop)))))
  writes)

(define v : (Vectorof Integer) (vector 5 4 3 2 1))
(cycle-sort! v)
(displayln v)
