cmake_minimum_required(VERSION 3.20)
project(MergeSort)

function(merge_sort result_var arr_str)
    string(REPLACE ";" " " arr_display "${arr_str}")
    list(LENGTH arr_str n)
    if(n LESS_EQUAL 1)
        set(${result_var} "${arr_str}" PARENT_SCOPE)
        return()
    endif()
    math(EXPR mid "${n} / 2")
    list(SUBLIST arr_str 0 ${mid} left_part)
    math(EXPR right_start "${mid}")
    list(SUBLIST arr_str ${right_start} -1 right_part)
    merge_sort(left_sorted "${left_part}")
    merge_sort(right_sorted "${right_part}")
    set(merged)
    set(li 0)
    set(ri 0)
    list(LENGTH left_sorted ln)
    list(LENGTH right_sorted rn)
    while(li LESS ln AND ri LESS rn)
        list(GET left_sorted ${li} lv)
        list(GET right_sorted ${ri} rv)
        if(lv LESS_EQUAL rv)
            list(APPEND merged ${lv})
            math(EXPR li "${li} + 1")
        else()
            list(APPEND merged ${rv})
            math(EXPR ri "${ri} + 1")
        endif()
    endwhile()
    while(li LESS ln)
        list(GET left_sorted ${li} lv)
        list(APPEND merged ${lv})
        math(EXPR li "${li} + 1")
    endwhile()
    while(ri LESS rn)
        list(GET right_sorted ${ri} rv)
        list(APPEND merged ${rv})
        math(EXPR ri "${ri} + 1")
    endwhile()
    set(${result_var} "${merged}" PARENT_SCOPE)
endfunction()

set(arr 38 27 43 3 9 82 10)
merge_sort(sorted "${arr}")
message(STATUS "Sorted: ${sorted}")
