(DEFUN INSERT (NODE VAL)
  (COND
    ((NULL NODE) (LIST VAL NIL NIL))
    ((< VAL (CAR NODE)) (LIST (CAR NODE) (INSERT (CADR NODE) VAL) (CADDR NODE)))
    ((> VAL (CAR NODE)) (LIST (CAR NODE) (CADR NODE) (INSERT (CADDR NODE) VAL)))
    (T NODE)))

(DEFUN INORDER (NODE)
  (COND
    ((NULL NODE) NIL)
    (T (APPEND (INORDER (CADR NODE))
               (CONS (CAR NODE) (INORDER (CADDR NODE)))))))

(DEFUN TREESORT (ARR)
  (INORDER (REDUCE 'INSERT ARR NIL)))

(PRINT (TREESORT '(5 2 8 1 9 3)))
